[env]
TERM = "xterm-256color"

[window]
opacity = 0.95

[font]
size = 13.5

[font.bold]
family = "Jet Brains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Jet Brains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Jet Brains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Jet Brains Mono Nerd Font"
style = "Regular"
