unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s

bind-key j select-pane -D
bind-key h select-pane -L
bind-key k select-pane -U
bind-key l select-pane -R

set -g base-index 1
setw -g pane-base-index 1

set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jimeh/tmuxifier'

run '~/.tmux/plugins/tpm/tpm'
