#### COLOUR (Rose Pine Dawn)

# Core styles
set -g mode-style "fg=#575279,bg=#f2e9e1"
set -g message-style "fg=#575279,bg=#f2e9e1"
set -g message-command-style "fg=#575279,bg=#f2e9e1"

# Pane borders
set -g pane-border-style "fg=#b9b4c9"
set -g pane-active-border-style "fg=#286983"

# Status bar
set -g status "on"
set -g status-interval 1
set -g status-justify "left"
set -g status-style "fg=#797593,bg=#faf4ed"
set -g status-left-length "100"
set -g status-right-length "100"
set -g status-left-style NONE
set -g status-right-style NONE

# Panes and clock
set -g display-panes-active-colour "#56949f"
set -g display-panes-colour "#b4637a"
setw -g clock-mode-colour "#286983"

# Left/right sections
set -g status-right "#[fg=#56949f,bg=#faf4ed,nobold,nounderscore,noitalics]#[fg=#faf4ed,bg=#56949f,bold] donghia "
set -g status-left "#[fg=#faf4ed,bg=#286983,bold] #S #[fg=#286983,bg=#faf4ed]"

# Windows
setw -g window-status-activity-style "underscore,fg=#575279,bg=#faf4ed"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#575279,bg=#faf4ed"
setw -g window-status-format '#[fg=#faf4ed,bg=#faf4ed]#[default] #I  #W #[fg=#faf4ed,bg=#faf4ed,nobold,nounderscore,noitalics]'
setw -g window-status-current-format '#[fg=#faf4ed,bg=#fffaf3]#[fg=#907aa9,bg=#fffaf3] #I #[fg=#fffaf3,bg=#907aa9] #W #[fg=#907aa9,bg=#faf4ed,nobold]'
