#### COLOUR (Solarized Light)

# Core styles
set -g mode-style "fg=#586e75,bg=#eee8d5"
set -g message-style "fg=#586e75,bg=#eee8d5"
set -g message-command-style "fg=#586e75,bg=#eee8d5"

# Pane borders
set -g pane-border-style "fg=#93a1a1"
set -g pane-active-border-style "fg=#268bd2"

# Status bar
set -g status "on"
set -g status-interval 1
set -g status-justify "left"
set -g status-style "fg=#657b83,bg=#eee8d5"
set -g status-left-length "100"
set -g status-right-length "100"
set -g status-left-style NONE
set -g status-right-style NONE

# Panes and clock
set -g display-panes-active-colour "#2aa198"
set -g display-panes-colour "#dc322f"
setw -g clock-mode-colour "#268bd2"

# Left/right sections
set -g status-right "#[fg=#2aa198,bg=#eee8d5,nobold,nounderscore,noitalics]#[fg=#eee8d5,bg=#2aa198,bold] donghia "
set -g status-left "#[fg=#eee8d5,bg=#268bd2,bold] #S #[fg=#268bd2,bg=#eee8d5]"

# Windows
setw -g window-status-activity-style "underscore,fg=#586e75,bg=#eee8d5"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#586e75,bg=#eee8d5"
setw -g window-status-format '#[fg=#eee8d5,bg=#eee8d5]#[default] #I  #W #[fg=#eee8d5,bg=#eee8d5,nobold,nounderscore,noitalics]'
setw -g window-status-current-format '#[fg=#eee8d5,bg=#fdf6e3]#[fg=#6c71c4,bg=#fdf6e3] #I #[fg=#fdf6e3,bg=#6c71c4] #W #[fg=#6c71c4,bg=#eee8d5,nobold]'
