return {
  --
  -- {
  --   'hrsh7th/cmp-nvim-lsp',
  -- },
  -- {
  --   'L3MON4D3/LuaSnip',
  --   dependencies = {
  --     'saadparwaiz1/cmp_luasnip',
  --     'rafamadriz/friendly-snippets',
  --   },
  --   config = function()
  --     -- local luasnip = require 'luasnip'
  --
  --
  --     -- luasnip.filetype_extend('javascriptreact', { 'html' })
  --     -- luasnip.filetype_extend('typescriptreact', { 'html' })
  --   end,
  -- },
  -- {
  --   'hrsh7th/nvim-cmp',
  --   version = false,
  --   config = function()
  --     local cmp = require 'cmp'
  --
  --     require('luasnip.loaders.from_vscode').lazy_load()
  --     cmp.setup {
  --       snippet = {
  --         expand = function(args)
  --           require('luasnip').lsp_expand(args.body)
  --         end,
  --       },
  --       sources = cmp.config.sources({
  --         { name = 'luasnip' },
  --         { name = 'nvim_lsp' },
  --       }, {
  --         { name = 'buffer' },
  --       }),
  --     }
  --   end,
  -- },
}
