font_family Jet Brains Mono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14

background_opacity 0.925

# ## SOLARIZED_DARK_HIGHER_CONTRAST
# background            #001e26
# foreground            #9bc1c2
# cursor                #f34a00
# selection_background  #003747
# color0                #002731
# color8                #006388
# color1                #d01b24
# color9                #f4153b
# color2                #6bbe6c
# color10               #50ee84
# color3                #a57705
# color11               #b17e28
# color4                #2075c7
# color12               #178dc7
# color5                #c61b6e
# color13               #e14d8e
# color6                #259185
# color14               #00b29e
# color7                #e9e2cb
# color15               #fcf4dc
# selection_foreground #001e26

# ## Kanagawa Alacritty Colors for Kitty
# Primary colors
background #1f1f28
foreground #dcd7ba

# Normal colors
color0 #090618
color1 #c34043
color2 #76946a
color3 #c0a36e
color4 #7e9cd8
color5 #957fb8
color6 #6a9589
color7 #c8c093

# Bright colors
color8 #727169
color9 #e82424
color10 #98bb6c
color11 #e6c384
color12 #7fb4ca
color13 #938aa9
color14 #7aa89f
color15 #dcd7ba

# Selection colors
selection_background #2d4f67
selection_foreground #c8c093

# Indexed colors
color16 #ffa066
color17 #ff5d62
